modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/SmellyModder/Architects-Palette/issues"

[[mods]]
    modId="architects_palette"
    namespace="architects_palette"
    version="1.0"
    displayName="Architect's Palette"
     # bro idk if i like having my name at the front but that seems to be the way to do it
     # technically i *am* the dev since im coding it all, but the whole point is the art and design, which i didnt do
     # kinda fucked up
    authors="Jsburg, SmellyModder, Snakeblock, THX, Smash Brothers, Orisghost, Mista Jub"
    description='''A mod that adds new stylish and unique building blocks'''
    displayURL=""
    [[dependencies.architects_palette]]
        modId="forge"
        mandatory=true
        versionRange="[${forge_version},)"
        ordering="NONE"